/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_82c9b25991a51e168e2e37d79e4b981d/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
  }
}
