/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/audit-log/': RouteRecordInfo<
      '/audit-log/',
      '/audit-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/[type]/': RouteRecordInfo<
      '/content/[type]/',
      '/content/:type',
      { type: ParamValue<true> },
      { type: ParamValue<false> },
      | never
    >,
    '/content/[type]/[uuid]/': RouteRecordInfo<
      '/content/[type]/[uuid]/',
      '/content/:type/:uuid',
      { type: ParamValue<true>, uuid: ParamValue<true> },
      { type: ParamValue<false>, uuid: ParamValue<false> },
      | never
    >,
    '/content/[type]/[uuid]/versions': RouteRecordInfo<
      '/content/[type]/[uuid]/versions',
      '/content/:type/:uuid/versions',
      { type: ParamValue<true>, uuid: ParamValue<true> },
      { type: ParamValue<false>, uuid: ParamValue<false> },
      | never
    >,
    '/developers/api-keys/': RouteRecordInfo<
      '/developers/api-keys/',
      '/developers/api-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/developers/api-reference/': RouteRecordInfo<
      '/developers/api-reference/',
      '/developers/api-reference',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/developers/documentation/': RouteRecordInfo<
      '/developers/documentation/',
      '/developers/documentation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/developers/webhooks/': RouteRecordInfo<
      '/developers/webhooks/',
      '/developers/webhooks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forgot-password': RouteRecordInfo<
      '/forgot-password',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-password': RouteRecordInfo<
      '/reset-password',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup': RouteRecordInfo<
      '/setup',
      '/setup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/verify-otp': RouteRecordInfo<
      '/verify-otp',
      '/verify-otp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/audit-log/index.vue': {
      routes:
        | '/audit-log/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/content/[type]/index.vue': {
      routes:
        | '/content/[type]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/content/[type]/[uuid]/index.vue': {
      routes:
        | '/content/[type]/[uuid]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/content/[type]/[uuid]/versions.vue': {
      routes:
        | '/content/[type]/[uuid]/versions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/developers/api-keys/index.vue': {
      routes:
        | '/developers/api-keys/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/developers/api-reference/index.vue': {
      routes:
        | '/developers/api-reference/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/developers/documentation/index.vue': {
      routes:
        | '/developers/documentation/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/developers/webhooks/index.vue': {
      routes:
        | '/developers/webhooks/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/forgot-password.vue': {
      routes:
        | '/forgot-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reset-password.vue': {
      routes:
        | '/reset-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/setup.vue': {
      routes:
        | '/setup'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/verify-otp.vue': {
      routes:
        | '/verify-otp'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
